/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exempluinterfataprolog;

import java.awt.FlowLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.io.PipedOutputStream;
import java.io.PrintStream;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Irina
 */
public class Fereastra extends javax.swing.JFrame {

    /**
     * Creates new form Fereastra
     * @param titlu
     */
    ConexiuneProlog conexiune;
    Intrebare_intrebatoare panou_intrebari;
    public Fereastra(String titlu) {
        super(titlu);
        panou_intrebari=new Intrebare_intrebatoare();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupBtn = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDebug = new javax.swing.JTextArea();
        b_incarca = new javax.swing.JButton();
        b_consulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textAreaDebug.setColumns(20);
        textAreaDebug.setRows(5);
        jScrollPane1.setViewportView(textAreaDebug);

        b_incarca.setText("Incarca regulile");
        b_incarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_incarcaActionPerformed(evt);
            }
        });

        b_consulta.setText("Va simtiti rau? Aflati diagnosticul pentru simptomele dumneavoastra.");
        b_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_consultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(b_consulta)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(b_incarca)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_incarca)
                .addGap(31, 31, 31)
                .addComponent(b_consulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_incarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_incarcaActionPerformed
        Fereastra.AFISAT_SOLUTII=false;
        String valoareParametru= "'reguli.txt'";
        //tfFisier.setEnabled(false);
        String dir=System.getProperty("user.dir");
        dir=dir.replace("\\", "/");
        try {
            conexiune.expeditor.trimiteMesajSicstus("director('"+dir+"')");
            conexiune.expeditor.trimiteMesajSicstus("incarca("+valoareParametru+")");
            
        
        } catch (InterruptedException ex) {
            Logger.getLogger(Fereastra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_b_incarcaActionPerformed

    private String readFile(String pathname) throws IOException {

        File file = new File(pathname);
        StringBuilder fileContents = new StringBuilder((int)file.length());
        Scanner scanner = new Scanner(file);
        String lineSeparator = System.getProperty("line.separator");

        try {
            while(scanner.hasNextLine()) {
                fileContents.append(scanner.nextLine() + lineSeparator);
            }
            return fileContents.toString();
        } finally {
            scanner.close();
        }
    }
    
    private void b_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_consultaActionPerformed
       
        this.remove(this.b_incarca);
        this.remove(this.b_consulta);
        //this.remove(this.tfFisier);
        
        this.setLayout(new FlowLayout());
        this.add(this.panou_intrebari);
        this.panou_intrebari.paint(null);
        this.panou_intrebari.revalidate();
        this.repaint();
        this.revalidate();
        try {
            conexiune.expeditor.trimiteMesajSicstus("comanda(consulta)");
            
        
        } catch (InterruptedException ex) {
            Logger.getLogger(Fereastra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_consultaActionPerformed

    
     private void optiuneButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
       
       
        String raspuns= ((JButton)(evt.getSource())).getText();
        try {
            conexiune.expeditor.trimiteSirSicstus(raspuns);
            
        
        } catch (InterruptedException ex) {
            Logger.getLogger(Fereastra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fereastra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fereastra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fereastra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fereastra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fereastra("Verificare").setVisible(true);
                
            }
        });
    }

    public javax.swing.JTextArea getDebugTextArea(){
        return textAreaDebug;
    }
    
    
    public void setConexiune(ConexiuneProlog _conexiune){
        conexiune=_conexiune;
    }
    public void setIntrebare(String intreb){
        this.panou_intrebari.label_intrebare.setText("<html><body style='width:100%'>"+intreb+"</html>");
        System.out.print(intreb);
        this.panou_intrebari.repaint();
    }
     public void setOptiuni(String optiuni){
        this.panou_intrebari.panou_optiuni.removeAll();
        this.panou_intrebari.panou_optiuni.setLayout(new FlowLayout());
        optiuni=optiuni.trim();
        optiuni=optiuni.substring(1,optiuni.length()-1);
        optiuni=optiuni.trim();
        String[] vect_opt=optiuni.split(" ");
        for(int i=0;i<vect_opt.length;i++)
        {
            JButton b=new JButton(vect_opt[i]);
            b.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    optiuneButtonActionPerformed(evt);
                }
            });
            this.panou_intrebari.panou_optiuni.add(b);
        }
        this.panou_intrebari.panou_optiuni.repaint();
        this.panou_intrebari.panou_optiuni.revalidate();
        //this.revalidate();
    }  

     public void setSolutie(String solutie){
        if(!Fereastra.AFISAT_SOLUTII)
        {
            this.panou_intrebari.removeAll();
            this.panou_intrebari.setLayout(new FlowLayout());
            Fereastra.AFISAT_SOLUTII=true;
        }

        JLabel jsol=new JLabel(solutie);
        this.panou_intrebari.add(jsol);
       

        this.panou_intrebari.repaint();
        this.panou_intrebari.revalidate();
        //this.revalidate();
    } 
    
    public static boolean AFISAT_SOLUTII=false;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_consulta;
    private javax.swing.JButton b_incarca;
    private javax.swing.ButtonGroup grupBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaDebug;
    // End of variables declaration//GEN-END:variables
}
